<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_clickclassname</name>
   <tag></tag>
   <elementGuidId>a9530ecb-fbca-48ae-ae85-fef37609b50f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'内部测试数据-考研混合类普通课表')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.p-list__sub-class__block__title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>550c48ae-2748-4c97-82d2-d329f2d30b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>内部测试数据-考研混合类普通课表</value>
      <webElementGuid>5cf1fe63-7d2c-459f-ad9b-77e25dbd4726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>bc2d20c4-7bf0-4150-a940-92d6431a0eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-list__sub-class__block__title</value>
      <webElementGuid>728973c3-caaf-4800-ba8a-380e8a8c4de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>内部测试数据-考研混合类普通课表</value>
      <webElementGuid>33e5b403-6ce5-4b88-b406-793fac6dbb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;home-content&quot;]/div[@class=&quot;i-wrap&quot;]/div[@class=&quot;i-wrap__main&quot;]/div[@class=&quot;p-list&quot;]/div[@class=&quot;p-list__group&quot;]/div[@class=&quot;p-list__item p-list__item--height-free p-list__item--goto-study&quot;]/div[@class=&quot;p-list__main p-list__main--blocked&quot;]/div[@class=&quot;p-list__sub-class p-list__sub-class__block-wrap&quot;]/div[@class=&quot;p-list__sub-class__block p-list__sub-class__block__all&quot;]/div[@class=&quot;p-list__sub-class__block__title-wrapper&quot;]/a[@class=&quot;p-list__sub-class__block__title&quot;]</value>
      <webElementGuid>aca0f65b-6f5e-4bb3-9133-715ce07ba9ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'内部测试数据-考研混合类普通课表')]</value>
      <webElementGuid>9c790873-d160-44ec-830e-0aeb78ce329c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/following::a[1]</value>
      <webElementGuid>e1a01e59-2c93-401b-8cce-39cd040f7a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='延期'])[1]/following::a[1]</value>
      <webElementGuid>bd972557-3fcd-4ca8-90e8-58e166d8f981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='已学：'])[1]/preceding::a[1]</value>
      <webElementGuid>33db8389-f6e5-47fe-b89d-27c83dbcbdeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='内部测试数据-考研混合类普通课表']/parent::*</value>
      <webElementGuid>0007e18e-9e36-4b04-bb69-90e7b11411a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/a</value>
      <webElementGuid>5c4cb73f-ed25-44ef-9157-166b134dd47b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = '内部测试数据-考研混合类普通课表' and (text() = '内部测试数据-考研混合类普通课表' or . = '内部测试数据-考研混合类普通课表')]</value>
      <webElementGuid>29c27245-dbfd-46d7-9b0f-e9e6ff34e3f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
