<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__password</name>
   <tag></tag>
   <elementGuidId>4c9fba6c-e177-4038-8719-ce4e8135547b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ant-input.css-1gfrjrs.ant-input-outlined.password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;请输入用户密码&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d755d88e-ca67-4b88-bdd5-02c603464661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>abfaf63b-edfc-49c0-8de3-7cc8aa3b1fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>请输入用户密码</value>
      <webElementGuid>9440f64c-1ff9-40ae-af3f-5f4e7cc1893e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3cec7377-726a-4679-95ba-9fc4c64a2c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>830df91d-eb9f-411b-8006-47555bb2c1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>adffeaa1-eedc-4fe9-8f8b-9f19d380c825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-1gfrjrs ant-input-outlined password</value>
      <webElementGuid>510a5155-c7ce-43c8-956d-5bed53c91560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-login-wrap&quot;)/div[@class=&quot;dxlogin-root&quot;]/div[@class=&quot;w-[384px] h-[530px] bg-white rounded-[8px] relative&quot;]/div[@class=&quot;dxlogin-root&quot;]/div[@class=&quot;box-content relative h-[458px] flex flex-col px-[52px] pt-[72px] text-[22px] font-[600] text-[#232A49] font-[&quot;PingFang SC&quot;]&quot;]/form[@class=&quot;ant-form ant-form-horizontal css-1gfrjrs flex-1 flex flex-col&quot;]/div[@class=&quot;ant-form-item css-1gfrjrs&quot;]/div[@class=&quot;ant-row ant-form-item-row css-1gfrjrs&quot;]/div[@class=&quot;ant-col ant-form-item-control css-1gfrjrs&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/div[@class=&quot;passwordBlock relative&quot;]/input[@class=&quot;ant-input css-1gfrjrs ant-input-outlined password&quot;]</value>
      <webElementGuid>8633d48a-941e-4115-83b4-9dbc3e53c9c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>e4e80c56-80b5-41b1-8454-b261e251e732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-login-wrap']/div/div/div[2]/div/form/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>83631032-c18a-4e0a-b830-282b29eaa98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/input</value>
      <webElementGuid>2550924d-76fc-4d58-8e12-e0360b569155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '请输入用户密码' and @type = 'password']</value>
      <webElementGuid>4d38d92b-8c31-4e76-89bd-e7f27dc59a4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
