<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_speed</name>
   <tag></tag>
   <elementGuidId>2a15444f-20c1-426e-a225-78dbb07d1a02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xdf-player_component_824658FD-B69C-46E3-AD86-7E0359BCE099']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.current-speed-selector</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>75b9f73e-ae09-4b58-9717-be8c324e55a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>current-speed-selector</value>
      <webElementGuid>aedf0552-ba1c-4a8b-9815-39f6066f2363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>key</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>33daa1e5-ed9e-401a-abe6-426bc861cfe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>97d5a534-61db-4b56-a768-1f6627028ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>倍速</value>
      <webElementGuid>7964ae92-5b72-4783-b586-0efc220c7e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xdf-player_component_824658FD-B69C-46E3-AD86-7E0359BCE099&quot;)/div[@class=&quot;current-speed-selector&quot;]</value>
      <webElementGuid>115f0784-b3a2-4596-9c0b-41d9a8baf5f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xdf-player_component_824658FD-B69C-46E3-AD86-7E0359BCE099']/div</value>
      <webElementGuid>fee3e819-93af-4605-8025-c495bb96151c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/following::div[3]</value>
      <webElementGuid>bda5e51f-36d6-4eb5-9539-6178b0ec4aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='正常'])[1]/preceding::div[2]</value>
      <webElementGuid>b94b61c8-e952-49ca-82aa-d926a4a28a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='确认'])[1]/preceding::div[14]</value>
      <webElementGuid>9c936970-3660-42b0-a41b-6e03ff4bcf2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='倍速']/parent::*</value>
      <webElementGuid>93c665fb-6e66-4a74-858a-3d002cd6c3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>5c988186-7304-461c-8e36-c78aafcc8dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '倍速' or . = '倍速')]</value>
      <webElementGuid>bf1b8c31-bb67-4a61-8da5-adab4bcb4655</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
