<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_speed-1.25X</name>
   <tag></tag>
   <elementGuidId>4283ea1d-9361-4e7f-b681-2805ee1419b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xdf-player_component_824658FD-B69C-46E3-AD86-7E0359BCE099']/ul/li[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.current</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4260f267-8f6b-448e-a587-64536c456397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>current</value>
      <webElementGuid>302d8da4-e9b3-4c7d-9e88-a4acd8e99d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1.25X</value>
      <webElementGuid>01c65465-0b94-453d-b164-5bfd8f35812e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xdf-player_component_824658FD-B69C-46E3-AD86-7E0359BCE099&quot;)/ul[@class=&quot;speed-selector-list&quot;]/li[3]/span[@class=&quot;current&quot;]</value>
      <webElementGuid>06ddaccb-a8e3-48a5-b47f-6d3d4a1dddfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xdf-player_component_824658FD-B69C-46E3-AD86-7E0359BCE099']/ul/li[3]/span</value>
      <webElementGuid>d50e2670-50c0-4014-868e-dd8c4a5533e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='正常'])[1]/following::span[1]</value>
      <webElementGuid>204bf5b5-b869-478a-8050-409acec3ee3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/following::span[4]</value>
      <webElementGuid>339405b6-d872-41a6-8b16-e41f85c9ea6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='确认'])[1]/preceding::span[3]</value>
      <webElementGuid>bccb1548-c3cd-4da9-b90f-71e4725dd9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='取消'])[2]/preceding::span[3]</value>
      <webElementGuid>130f8685-edc2-48f8-bfa4-016505819838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/ul/li[3]/span</value>
      <webElementGuid>d363e44c-d379-413d-9199-36744fee21dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1.25X' or . = '1.25X')]</value>
      <webElementGuid>ecd13143-5ec7-40a5-92ef-012935932aab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
