<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video</name>
   <tag></tag>
   <elementGuidId>3141bbf0-ff6e-481e-a7d8-96486d4cbcd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xdf-player']/div[19]/video</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>video</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>187026d2-0deb-4100-9799-407446101ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preload</name>
      <type>Main</type>
      <value>preload</value>
      <webElementGuid>7f118c8b-6098-4e13-b294-22c79b65d7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autoplay</name>
      <type>Main</type>
      <value>autoplay</value>
      <webElementGuid>fef74cce-97b3-4b7d-a112-0dffb8a17ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>crossorigin</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>f3707eef-30c7-4918-8734-7ffbdec4e190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://monitor-bj.roombox.xdf.cn/roombox/record/merged-2/2024/03/28/_5184759818e5cc15.mp4?auth_key=1717312732-e9795e67c5e04ca7810317b5123df7ab-0-08310b5e6be4c7e5c7cd3a9e98bae30e</value>
      <webElementGuid>79791a5d-b4f4-4c70-aea6-70354d283c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xdf-player&quot;)/div[19]/video[1]</value>
      <webElementGuid>1df7b862-aa38-4689-995f-a83634cd89f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xdf-player']/div[19]/video</value>
      <webElementGuid>d4cb0c43-1300-460d-a43c-0aa3cee51115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>d590d5d6-7a9d-455a-99e2-dba8330497d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@src = 'https://monitor-bj.roombox.xdf.cn/roombox/record/merged-2/2024/03/28/_5184759818e5cc15.mp4?auth_key=1717312732-e9795e67c5e04ca7810317b5123df7ab-0-08310b5e6be4c7e5c7cd3a9e98bae30e']</value>
      <webElementGuid>92418290-2e4c-4d41-8bbd-eb886b90b66f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
