<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_01-4</name>
   <tag></tag>
   <elementGuidId>18aceb41-39aa-479f-9ae3-d514c024fa92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jp-content-wrap']/div/div/div/div[2]/div[3]/ul/li/ul/li/ul/li[3]/div/div/p/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span[title=&quot;【内部测试】新录播课平台01-4个清晰度&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bb6b44f4-6efc-4b5e-86a5-0ce227afa748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>【内部测试】新录播课平台01-4个清晰度</value>
      <webElementGuid>a9cbb1f0-df6d-4587-997a-e394f3e24105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>【内部测试】新录播课平台01-4个清晰度</value>
      <webElementGuid>5baeec8c-76e2-4b76-b3c1-6b59f30dae91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jp-content-wrap&quot;)/div[@class=&quot;content-item jp-menu-wrap&quot;]/div[@class=&quot;inner-content-item-with-path&quot;]/div[@class=&quot;list-container&quot;]/div[@class=&quot;jp-sub-list-container&quot;]/div[@class=&quot;jp-list-container&quot;]/ul[@class=&quot;chapter&quot;]/li[@class=&quot;jp-filter&quot;]/ul[@class=&quot;bd jp-bd&quot;]/li[@class=&quot;sub-hd-wrap jp-node-wrap jp-filter&quot;]/ul[@class=&quot;sub-bd jp-sub-bd package-sub-bd-wrap&quot;]/li[@class=&quot;class-wrap jp-leaf-wrap jp-filter&quot;]/div[@class=&quot;jp-sub-third-bd&quot;]/div[@class=&quot;class-item jp-class-item jp-filter&quot;]/p[@class=&quot;title&quot;]/span[1]</value>
      <webElementGuid>c476b613-f894-4cd7-bc27-9c07d25b5e43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jp-content-wrap']/div/div/div/div[2]/div[3]/ul/li/ul/li/ul/li[3]/div/div/p/span</value>
      <webElementGuid>600fbf93-dcbe-4445-8bb0-4be684c59e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alice002-直播课-02'])[1]/following::span[2]</value>
      <webElementGuid>0db38259-ba01-4b68-ae15-9c542224aac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alice001-录播课-01'])[1]/following::span[4]</value>
      <webElementGuid>b4d839b2-fd44-4a35-a39f-5cd9971fc482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='上次学习'])[1]/preceding::span[1]</value>
      <webElementGuid>d3287b1b-42fc-450a-97ee-c7f238a0bd0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='【内部测试】新录播课平台02-4个清晰度'])[1]/preceding::span[4]</value>
      <webElementGuid>bd1c2990-be51-41cf-9eb0-0a31ab8d280b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='【内部测试】新录播课平台01-4个清晰度']/parent::*</value>
      <webElementGuid>f71ffb21-609d-42d5-99d7-08e2c92339b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/p/span</value>
      <webElementGuid>1b9d5ed7-24f3-486b-89ed-23fe28a71308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = '【内部测试】新录播课平台01-4个清晰度' and (text() = '【内部测试】新录播课平台01-4个清晰度' or . = '【内部测试】新录播课平台01-4个清晰度')]</value>
      <webElementGuid>df8c5dd7-1a3b-41c0-958d-d872ba4feef9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
