<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1.5X</name>
   <tag></tag>
   <elementGuidId>1387efe4-43f8-43b2-848b-e77335b7e4eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xdf-player_component_4DA129DC-3563-4532-8336-48550B77EA32']/ul/li[4]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.speed-selector-list > li:nth-of-type(4) > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;1.5X&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b12f427a-8d79-4773-9ee5-6da5070b374e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1.5X</value>
      <webElementGuid>1c13d355-c671-41a4-a3c8-88e4f398acd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xdf-player_component_4DA129DC-3563-4532-8336-48550B77EA32&quot;)/ul[@class=&quot;speed-selector-list&quot;]/li[4]/span[1]</value>
      <webElementGuid>e06478ee-434e-4ca0-b344-640fbcdc4979</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xdf-player_component_4DA129DC-3563-4532-8336-48550B77EA32']/ul/li[4]/span</value>
      <webElementGuid>5756816d-723c-4491-890c-516963d10933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='正常'])[1]/following::span[2]</value>
      <webElementGuid>e9cff0d8-94c7-4c47-801b-3bf8c596092c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='倍速'])[1]/following::span[4]</value>
      <webElementGuid>70d023db-889a-408e-bd2c-7ec6656609ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='确认'])[1]/preceding::span[2]</value>
      <webElementGuid>26948ad0-4892-4c89-b700-adbd9a2215cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='取消'])[2]/preceding::span[2]</value>
      <webElementGuid>12423f4f-0ab6-4881-b481-c9399dc69933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1.5X']/parent::*</value>
      <webElementGuid>f6f6c2a0-b13f-40c2-bfad-383948d9d222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li[4]/span</value>
      <webElementGuid>a57082d3-16e9-4e0d-86b7-19abc31e994a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1.5X' or . = '1.5X')]</value>
      <webElementGuid>eb1bc219-b5ec-4cb0-903f-bed712d89fa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
