<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__1</name>
   <tag></tag>
   <elementGuidId>49d594b3-b094-4723-9f2f-4c06f0b23a31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.regist-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='《儿童隐私保护政策》'])[1]/following::div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dbbf9534-cfcd-4d6f-9236-65ec666541b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>regist-button</value>
      <webElementGuid>fc35788f-4e60-48cf-a581-f1375ed5070c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>登录</value>
      <webElementGuid>ea186e61-7802-4df6-a2c8-b303068305ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;dxlogin-root&quot;]/div[@class=&quot;box-content w-screen h-screen fixed inset-x-0 bg-mask opacity-100 flex justify-center items-center top-0 left-0&quot;]/div[@class=&quot;w-[384px] h-[530px] bg-white rounded-[8px] relative&quot;]/div[@class=&quot;dxlogin-root&quot;]/div[@class=&quot;box-content relative h-[458px] flex flex-col px-[52px] pt-[72px] text-[22px] font-[600] text-[#232A49] font-[&quot;PingFang SC&quot;]&quot;]/div[@class=&quot;bottom-block&quot;]/div[@class=&quot;regist-button&quot;]</value>
      <webElementGuid>824b90b6-90f0-429f-8990-7afe3175c4d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='《儿童隐私保护政策》'])[1]/following::div[2]</value>
      <webElementGuid>53be209f-dfdd-4b10-92da-0a497b0ccd13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='《隐私保护政策》'])[1]/following::div[2]</value>
      <webElementGuid>9478dfdf-931a-4737-9b9f-0ac67f4cb8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='验证码登录'])[1]/preceding::div[1]</value>
      <webElementGuid>9c6fd63f-208e-4e55-81a2-1ae75c816b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='国际手机号登录'])[1]/preceding::div[1]</value>
      <webElementGuid>764b63d0-fd8b-4828-b7ac-832a48144382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='登录']/parent::*</value>
      <webElementGuid>36ca458e-715b-4f20-b8d3-ef50bf068fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>9e975f44-9881-4bde-924a-d1aa07718a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '登录' or . = '登录')]</value>
      <webElementGuid>040d5795-d03f-484e-a707-220ad86b04c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
