<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_25</name>
   <tag></tag>
   <elementGuidId>e3d25a5e-3a29-40b7-8eac-18dfc040cebf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.styles_sub-title-wrap-content__2n49A</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/div/ul/li/div[2]/a/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>304197e5-c228-4c52-b14c-4319c64b1382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_sub-title-wrap-content__2n49A</value>
      <webElementGuid>0cacf406-473c-4d90-b53c-d1ae9cc5db83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>25考研</value>
      <webElementGuid>7dce8a61-374a-416c-a3c3-4e7c6c2b6693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;Home_container__3sao-&quot;]/div[@class=&quot;styles_top-hd-wrap__2Yn36&quot;]/div[@class=&quot;styles_slide-down-wrap__3d0D_ styles_bg__3v5aC styles_show__3QzhQ&quot;]/div[@class=&quot;styles_hd-content__8iKS6&quot;]/ul[@class=&quot;styles_links-list-wrap__3Ps-0&quot;]/li[@class=&quot;styles_links-item-wrap__2hsko&quot;]/div[@class=&quot;styles_sub-title-wrap__1weWP&quot;]/a[1]/div[@class=&quot;styles_sub-title__2qV1-&quot;]/span[@class=&quot;styles_sub-title-wrap-content__2n49A&quot;]</value>
      <webElementGuid>82f8e904-25a3-48e3-9fab-a1ceb00e1d36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/ul/li/div[2]/a/div/span[2]</value>
      <webElementGuid>d4f0d6d2-e9d5-4aaf-9056-254e4e5963e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='上岸好课 618抢先价'])[1]/following::span[2]</value>
      <webElementGuid>d35d18d4-361b-4f8b-b010-fbdc8834929d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='规则'])[1]/following::span[2]</value>
      <webElementGuid>8246d0c1-377a-4879-a7b6-4a913aa93922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='在职考研'])[1]/preceding::span[4]</value>
      <webElementGuid>dc64d59d-f163-44b8-829b-2e1ef17622e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='伴学抢跑全程班'])[1]/preceding::span[8]</value>
      <webElementGuid>81a8c8ef-94e2-4886-9e45-3c71f6eb505a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='25考研']/parent::*</value>
      <webElementGuid>f46fb686-5cf5-4540-9296-47abe0e5bb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/span[2]</value>
      <webElementGuid>33d73d60-7d15-47eb-90ce-6fc251ed47a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '25考研' or . = '25考研')]</value>
      <webElementGuid>aa80ac64-f8ef-47ef-8791-d071b6788d35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
