<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__checkbox-input</name>
   <tag></tag>
   <elementGuidId>40d37cfc-9f5b-45d0-8985-b0c3d581fb4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ant-checkbox-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb51f903-3092-40d0-8e06-0827f62ffa49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-checkbox-input</value>
      <webElementGuid>fafc5729-b014-46fa-8fe3-34e533a90e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5b28dfc7-fd03-40fa-9c3e-a3b73c639b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-login-wrap&quot;)/div[@class=&quot;dxlogin-root&quot;]/div[@class=&quot;w-[384px] h-[530px] bg-white rounded-[8px] relative&quot;]/div[@class=&quot;dxlogin-root&quot;]/div[@class=&quot;box-content relative h-[458px] flex flex-col px-[52px] pt-[72px] text-[22px] font-[600] text-[#232A49] font-[&quot;PingFang SC&quot;]&quot;]/form[@class=&quot;ant-form ant-form-horizontal css-1gfrjrs flex-1 flex flex-col&quot;]/div[@class=&quot;ant-form-item flex-1 flex flex-col justify-end css-1gfrjrs&quot;]/div[@class=&quot;ant-row ant-form-item-row css-1gfrjrs&quot;]/div[@class=&quot;ant-col ant-form-item-control css-1gfrjrs&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/div[@class=&quot;protocol relative&quot;]/label[@class=&quot;ant-checkbox-wrapper ant-checkbox-wrapper-in-form-item css-1gfrjrs&quot;]/span[@class=&quot;ant-checkbox ant-wave-target css-1gfrjrs&quot;]/input[@class=&quot;ant-checkbox-input&quot;]</value>
      <webElementGuid>fbf83b69-2589-4c3b-8036-6097b99d835e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>b126bd5b-d246-46a5-9634-c6a3f9ecfadf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-login-wrap']/div/div/div[2]/div/form/div[3]/div/div/div/div/div/label/span/input</value>
      <webElementGuid>9f31d8dd-53b6-40e7-a0a8-e93c4d5cc088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>f770dc35-9290-4433-9342-21ad0e15a4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>f8e4a742-a3ca-4b5f-a6f1-b2b6b7e33471</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
