<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__username</name>
   <tag></tag>
   <elementGuidId>290a31ce-02bc-4626-8e1b-10e3d11735de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ant-input.css-1gfrjrs.ant-input-outlined.username</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9719b542-32dc-4f61-be24-426f7a0fa52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>请输入手机号/用户名/注册邮箱</value>
      <webElementGuid>80b9b0f0-e03a-4bfb-9b15-68773135016d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-1gfrjrs ant-input-outlined username</value>
      <webElementGuid>a321ed08-5749-4ab5-8af1-72ba195aa65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>04a42de5-41e5-4852-87da-015d1ca689fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-login-wrap&quot;)/div[@class=&quot;dxlogin-root&quot;]/div[@class=&quot;w-[384px] h-[530px] bg-white rounded-[8px] relative&quot;]/div[@class=&quot;dxlogin-root&quot;]/div[@class=&quot;box-content relative h-[458px] flex flex-col px-[52px] pt-[72px] text-[22px] font-[600] text-[#232A49] font-[&quot;PingFang SC&quot;]&quot;]/form[@class=&quot;ant-form ant-form-horizontal css-1gfrjrs flex-1 flex flex-col&quot;]/div[@class=&quot;ant-form-item css-1gfrjrs&quot;]/div[@class=&quot;ant-row ant-form-item-row css-1gfrjrs&quot;]/div[@class=&quot;ant-col ant-form-item-control css-1gfrjrs&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/div[@class=&quot;relative usernameBlock&quot;]/input[@class=&quot;ant-input css-1gfrjrs ant-input-outlined username&quot;]</value>
      <webElementGuid>1dcc3d83-4b34-41c0-9333-89dfd19ac3a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>3961fb2e-d3ff-4458-8514-cc958c0dea5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-login-wrap']/div/div/div[2]/div/form/div/div/div/div/div/div/input</value>
      <webElementGuid>ed3cd4a2-f2c6-4fdc-b0e5-6bb527151223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>ac4bf767-b693-46ed-b387-029255019f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '请输入手机号/用户名/注册邮箱' and @type = 'text']</value>
      <webElementGuid>8722159a-0742-45c1-908e-713a94380f9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
