<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_clickpalybackbutton</name>
   <tag></tag>
   <elementGuidId>36eb11a8-9b2b-47fb-b623-983ee5b63f2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'看回放')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.live-detail__btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;看回放&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d188c8c5-aa1e-4e39-bfd0-a941ecad24eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>c72068c2-50a3-411b-bf2f-257135fbed92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>live-detail__btn</value>
      <webElementGuid>7e0b0460-adff-4041-bcf5-b7bb7e784c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>看回放</value>
      <webElementGuid>6ac44c80-0910-4523-890e-ab6ee60e3fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;i-content-wrap&quot;]/div[@class=&quot;i-content-inner p-content-inner g-clear&quot;]/div[@class=&quot;p-lesson-wrap i-content-block&quot;]/div[@class=&quot;p-lives&quot;]/div[@class=&quot;live-list&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;live&quot;]/div[@class=&quot;live-contents&quot;]/div[@class=&quot;live-content&quot;]/div[@class=&quot;live-detail&quot;]/div[@class=&quot;live-detail__inner&quot;]/a[@class=&quot;live-detail__btn&quot;]</value>
      <webElementGuid>b3a301b5-5bef-4e90-8a24-f90cb777e4d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'看回放')]</value>
      <webElementGuid>8a1ce356-ecc7-4d45-9269-a2fab44f8ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='已结束'])[1]/following::a[1]</value>
      <webElementGuid>7511152c-be4b-4677-8678-4a2b312581f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='我是有底线的噢'])[1]/preceding::a[1]</value>
      <webElementGuid>aa9db49c-fd25-4c35-9c9d-708cceeea9e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='看回放']/parent::*</value>
      <webElementGuid>32884bd6-d7f0-4e73-9ec8-49f9823adac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>ad4a3bff-2d92-434d-8729-de1ac03abe78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '看回放' or . = '看回放')]</value>
      <webElementGuid>a5e5c4d8-044f-4bc7-abae-773cc83abce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
