<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__clicksearchicon</name>
   <tag></tag>
   <elementGuidId>8c297e9d-6004-47bc-9cd2-0497af0bf17f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/b/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.pointer__icon.pointer__icon-glass</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(2) > .pointer > .pointer__icon</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f926047f-39fe-4f9e-861f-9014c3fd6944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer__icon pointer__icon-glass</value>
      <webElementGuid>d747932e-beab-424b-bd93-32162d4fb801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;i-content-wrap&quot;]/div[@class=&quot;i-content-inner p-content-inner g-clear&quot;]/div[@class=&quot;p-lesson-wrap i-content-block&quot;]/div[@class=&quot;p-lives&quot;]/div[@class=&quot;p-search&quot;]/div[@class=&quot;p-search__con&quot;]/div[@class=&quot;p-search__pickers&quot;]/div[@class=&quot;p-search__picker&quot;]/b[@class=&quot;pointer&quot;]/i[@class=&quot;pointer__icon pointer__icon-glass&quot;]</value>
      <webElementGuid>6441afc8-86bc-4176-b353-1f3e67b4e997</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/b/i</value>
      <webElementGuid>a3447cb3-3935-4cf4-b3a0-881d9b9a07f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
