<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__p-search__input</name>
   <tag></tag>
   <elementGuidId>cf6b24a9-e28a-40e7-a01b-99f8b949cad7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;按直播课名称、教师姓名搜索&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3cffe6f7-fcc8-4d91-b9e0-2652a6390a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae7bf3ad-8db4-4d36-8c43-6b93bd71eda5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>按直播课名称、教师姓名搜索</value>
      <webElementGuid>aaab5c7e-a8c7-409b-bcbb-525bbfc0d11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-search__input</value>
      <webElementGuid>5810b1d8-a4a4-4228-8590-e2d8604e16cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;i-content-wrap&quot;]/div[@class=&quot;i-content-inner p-content-inner g-clear&quot;]/div[@class=&quot;p-lesson-wrap i-content-block&quot;]/div[@class=&quot;p-lives&quot;]/div[@class=&quot;p-search&quot;]/div[@class=&quot;p-search__con&quot;]/div[@class=&quot;p-search__pickers&quot;]/div[@class=&quot;p-search__picker&quot;]/input[@class=&quot;p-search__input&quot;]</value>
      <webElementGuid>485b5c4f-7a91-470c-b459-79fdf3f987ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[3]</value>
      <webElementGuid>9dee8839-538a-49c2-a21d-0704d1a9eb06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>74c4165d-08b6-4c2f-a2a6-e49920bcdfaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '按直播课名称、教师姓名搜索']</value>
      <webElementGuid>a93e49c2-8090-44f8-9d7b-6e84803f972e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
