<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_player_speed1.5X</name>
   <tag></tag>
   <elementGuidId>8e5007da-91dd-46c3-9c2a-c95611c6f860</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@value='1.5']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#EDDCBDCBF5145 >> internal:text=&quot;1.5X&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c64d263a-f5ff-452d-b765-9d604e6a174a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-select-dropdown-option-item-content</value>
      <webElementGuid>8ae0aec0-bb20-43e9-a4be-a589c91e6ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1.5</value>
      <webElementGuid>200519da-2807-4311-8ea7-a52a1555d797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>1.5X</value>
      <webElementGuid>0c3f5ca3-f01f-4272-bc30-844326e52016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1.5X</value>
      <webElementGuid>05538cfb-de3b-487c-a423-341347215e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EDDCBDCBF5145&quot;)/div[5]/div[@class=&quot;dx-select-dropdown&quot;]/div[@class=&quot;dx-select-dropdown-option-item&quot;]/div[@class=&quot;dx-select-dropdown-option-item-content&quot;]</value>
      <webElementGuid>89fa0fd8-df91-4332-a96c-a043cd8ad261</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@value='1.5']</value>
      <webElementGuid>8c1259d0-3070-4699-8a64-014cd760c7e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EDDCBDCBF5145']/div[5]/div/div[3]/div</value>
      <webElementGuid>8ee83442-8c74-4f90-aaa6-b694d242de8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='取消'])[1]/following::div[10]</value>
      <webElementGuid>4f52781f-671a-4217-905d-ab0f939b6220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='确认'])[1]/following::div[10]</value>
      <webElementGuid>dc278719-108e-405d-bf63-e6e2e719022f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/preceding::div[14]</value>
      <webElementGuid>f90c7edd-2214-4080-bdf8-816ce0204207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='高清'])[1]/preceding::div[17]</value>
      <webElementGuid>d508264c-4dbf-46fb-926f-63e8eed8ae22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1.5X']/parent::*</value>
      <webElementGuid>a8afe252-e455-4bf5-9897-fa1cf1a8cb18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]/div</value>
      <webElementGuid>3d8802f8-4579-4470-b4c1-73a226f8ae2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = '1.5X' and (text() = '1.5X' or . = '1.5X')]</value>
      <webElementGuid>9b745e02-d2d1-4be0-83f0-a73420f5b1d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
