<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dx-palyer_speed</name>
   <tag></tag>
   <elementGuidId>90f18caf-0547-483b-b5ad-e2072b765be2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//dx-popover[@value='1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>dx-popover[value=&quot;1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>dx-popover</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>dx-popover</value>
      <webElementGuid>cfaaebcc-c3da-4ad6-a04d-088bfc102a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ssrtag</name>
      <type>Main</type>
      <value>EDDCBDCBF5145</value>
      <webElementGuid>8b3171cb-973f-4bfb-860c-4b6a15793c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>47831172-c23a-4643-a0e0-9fe986fff80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2.0X1.8X1.5X1.2X1.0X0.8X</value>
      <webElementGuid>765a5e26-b5ae-417c-b1fe-8cabdb2a1038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jp-player-wrap&quot;)/dx-player[1]/div[@class=&quot;dx-player&quot;]/div[@class=&quot;dx-player-controller&quot;]/div[@class=&quot;dx-player-controller-bottom&quot;]/div[@class=&quot;dx-player-controller-bottom-right&quot;]/div[@class=&quot;dx-player-controller-bottom-right-speed&quot;]/dx-popover[1]</value>
      <webElementGuid>b6bade17-77cc-42cb-9001-ec0ffb87ee4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//dx-popover[@value='1']</value>
      <webElementGuid>dc39e59f-cc7f-4a85-b071-d21370aa1968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jp-player-wrap']/dx-player/div/div[2]/div[2]/div[2]/div[3]/dx-popover</value>
      <webElementGuid>4fb66e6b-82a8-4fc6-bb1b-c1dbed25403a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='高清'])[1]/following::dx-popover[1]</value>
      <webElementGuid>dc633013-7c18-4669-a5d0-79f7de4ed7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/following::dx-popover[1]</value>
      <webElementGuid>b792a9e8-ff29-4fd9-a646-0982ec80f2a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='收藏视频'])[1]/preceding::dx-popover[1]</value>
      <webElementGuid>2915cac1-6225-4c2d-be9c-4a1bba60fc00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dx-popover</value>
      <webElementGuid>71ad7135-cb32-4f5a-8190-b3df57771c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//dx-popover[(text() = '2.0X1.8X1.5X1.2X1.0X0.8X' or . = '2.0X1.8X1.5X1.2X1.0X0.8X')]</value>
      <webElementGuid>8728583a-35c2-447b-8452-e83afed34dc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
