<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_2022VIP</name>
   <tag></tag>
   <elementGuidId>03bbe5f4-053c-44f5-9818-0afd64b6f435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='进入学习'])[9]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;【测试】2022考研直通车【政治长线VIP】（大咖版）秒杀产品&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cb4a835e-1258-43a5-9e7d-907c6ee1bca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-list__item-title__inner</value>
      <webElementGuid>9ee96801-96c2-4770-a7fd-9f5f789bcc7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  
                【测试】2022考研直通车【政治长线VIP】（大咖版）秒杀产品
            </value>
      <webElementGuid>3ccf4b75-19a5-4aef-91b5-3410e9dcbec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;home-content&quot;]/div[@class=&quot;i-wrap&quot;]/div[@class=&quot;i-wrap__main&quot;]/div[@class=&quot;p-list&quot;]/div[@class=&quot;p-list__group&quot;]/div[@class=&quot;p-list__item p-list__item--goto-study&quot;]/div[@class=&quot;p-list__main&quot;]/a[@class=&quot;p-list__item-title&quot;]/span[@class=&quot;p-list__item-title__inner&quot;]</value>
      <webElementGuid>1d3b9d71-9641-4fa7-9cd5-2f069a7cc7cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='进入学习'])[9]/following::span[1]</value>
      <webElementGuid>046f4b5a-186f-4a2a-893c-86942d6d3098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='置顶课程'])[6]/following::span[1]</value>
      <webElementGuid>205aee3f-bec8-487a-b67b-d3ef22081c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='有效时间：至2026-12-31'])[1]/preceding::span[1]</value>
      <webElementGuid>719a2ca1-6688-4635-a63c-763ab13bb870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='【测试】2022考研直通车【政治长线VIP】（大咖版）秒杀产品']/parent::*</value>
      <webElementGuid>28c0e10f-cf19-42b0-8407-bc4b689a782c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/a/span</value>
      <webElementGuid>a2fe38bf-a494-476e-bf47-0f2a77cc0677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '  
                【测试】2022考研直通车【政治长线VIP】（大咖版）秒杀产品
            ' or . = '  
                【测试】2022考研直通车【政治长线VIP】（大咖版）秒杀产品
            ')]</value>
      <webElementGuid>281c9bb7-68dd-4e09-80e5-cafa8453e5fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
