<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__clickxdfplayername</name>
   <tag></tag>
   <elementGuidId>d58b421a-42a5-47af-a208-2cf5e30bc3b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jp-content-wrap']/div/div/ul/li/ul/li/ul/div/p/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span[title=&quot;毛中特选择题&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;毛中特选择题&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2067ceec-30aa-4098-a7b9-10196753cc65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>毛中特选择题</value>
      <webElementGuid>043e6c3e-7dfc-45e4-920d-d4aea7c20877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>毛中特选择题</value>
      <webElementGuid>55b91a9c-aad8-434f-a321-c6cbb526f255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jp-content-wrap&quot;)/div[@class=&quot;content-item jp-menu-wrap&quot;]/div[@class=&quot;list-container jp-list-container&quot;]/ul[@class=&quot;chapter&quot;]/li[@class=&quot;jp-filter&quot;]/ul[@class=&quot;bd jp-bd&quot;]/li[@class=&quot;sub-hd-wrap jp-node-wrap jp-filter&quot;]/ul[@class=&quot;sub-bd jp-sub-bd&quot;]/div[@class=&quot;class-item jp-class-item jp-filter&quot;]/p[@class=&quot;title&quot;]/span[1]</value>
      <webElementGuid>04fa7275-37e7-46b9-b3ca-f88cd1590b9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jp-content-wrap']/div/div/ul/li/ul/li/ul/div/p/span</value>
      <webElementGuid>61f39ce1-7e81-4049-96dc-779d5b2bc9c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='更新中，课时：10'])[1]/following::span[1]</value>
      <webElementGuid>553b4bca-ad94-415c-b19f-4686f8677236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='阮晔、测试老师55、杜成强、金格妃、测试ceshi'])[1]/following::span[3]</value>
      <webElementGuid>5a5b8e46-ee93-44fa-b9ba-9401b0dea1e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='上次学习'])[1]/preceding::span[1]</value>
      <webElementGuid>fc30889b-14b3-4fb8-ab1e-e0caa3791ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='【内部测试数据】20230913 22:15-22:30'])[1]/preceding::span[4]</value>
      <webElementGuid>d64a1283-36c1-4f4f-8902-83d1ebb72b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='毛中特选择题']/parent::*</value>
      <webElementGuid>fc64929e-add0-4270-a3a4-92c4e11807f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div/p/span</value>
      <webElementGuid>3a9486eb-88df-46d1-ab30-4749792d906d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = '毛中特选择题' and (text() = '毛中特选择题' or . = '毛中特选择题')]</value>
      <webElementGuid>3df7797b-3390-4543-9bf0-9e9393b8e692</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
