<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>24b85898-f504-4b65-aa02-45c0de8c74e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;全部课程&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c120ac41-e775-4885-bc83-20dbd8efd082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>second-nav-url--KCXN5qu</value>
      <webElementGuid>1c7c2734-0a17-4d28-8296-af4ab31232d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>全部课程</value>
      <webElementGuid>33e67d77-563f-4b67-aee2-0cf6ce0c1186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;second-nav-wrap--3qtATEH&quot;]/div[@class=&quot;second-nav-content--2kkWcGI&quot;]/div[@class=&quot;second-nav-right--Zo54qF1&quot;]/span[@class=&quot;second-nav-url--KCXN5qu&quot;]</value>
      <webElementGuid>d433d328-2388-44df-aeaa-91f00f9c496c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/span[2]</value>
      <webElementGuid>84c28660-399d-487e-8e28-416fb3a20be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='首页'])[1]/following::span[1]</value>
      <webElementGuid>b75305d8-bb8d-4969-8117-9a927bf4c486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='有效期：至2026-12-31'])[1]/following::span[2]</value>
      <webElementGuid>c639fe09-09fb-4059-9a23-fc34ac44ed2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='今日任务'])[1]/preceding::span[1]</value>
      <webElementGuid>5c53001e-fffa-4d62-9bb5-56290a12394e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='全部任务'])[1]/preceding::span[1]</value>
      <webElementGuid>fb391141-66d3-4452-b315-029cf9109379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='全部课程']/parent::*</value>
      <webElementGuid>b15b86b5-d99a-4bfd-aeab-cf7a1ee5b6ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>51d4e0fa-27a8-420a-87c6-edd33805dc57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '全部课程' or . = '全部课程')]</value>
      <webElementGuid>f1d4f60d-298c-45b9-a8fc-6fe6eba7a2c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
