<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__loginusername</name>
   <tag></tag>
   <elementGuidId>f3d523ce-3c22-4c5b-b412-d7269e4ecf72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ant-input.css-1gfrjrs.ant-input-outlined.username</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;请输入手机号/用户名/注册邮箱&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b2b2d15-18c3-491f-9e5d-2e2e928303f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>请输入手机号/用户名/注册邮箱</value>
      <webElementGuid>470b542e-d1a5-45d3-9427-ff4e311dfa26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-1gfrjrs ant-input-outlined username</value>
      <webElementGuid>039150de-98f2-4caa-a072-9399cbbb9253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bee3412c-373f-433d-a834-b4460554ab69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-login-wrap&quot;)/div[@class=&quot;dxlogin-root&quot;]/div[@class=&quot;w-[384px] h-[530px] bg-white rounded-[8px] relative&quot;]/div[@class=&quot;dxlogin-root&quot;]/div[@class=&quot;box-content relative h-[458px] flex flex-col px-[52px] pt-[72px] text-[22px] font-[600] text-[#232A49] font-[&quot;PingFang SC&quot;]&quot;]/form[@class=&quot;ant-form ant-form-horizontal css-1gfrjrs flex-1 flex flex-col&quot;]/div[@class=&quot;ant-form-item css-1gfrjrs&quot;]/div[@class=&quot;ant-row ant-form-item-row css-1gfrjrs&quot;]/div[@class=&quot;ant-col ant-form-item-control css-1gfrjrs&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/div[@class=&quot;relative usernameBlock&quot;]/input[@class=&quot;ant-input css-1gfrjrs ant-input-outlined username&quot;]</value>
      <webElementGuid>2b3932e7-e931-4373-bd78-8eda1301ad94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>2c3354e6-0ebe-4336-9ce9-040d220dcf18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-login-wrap']/div/div/div[2]/div/form/div/div/div/div/div/div/input</value>
      <webElementGuid>e742e080-f84b-41b5-94c0-1cae641a2635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>6cdb673c-5d6a-49c7-81b1-f7451fa3a2ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '请输入手机号/用户名/注册邮箱' and @type = 'text']</value>
      <webElementGuid>b29c7b03-d144-48b3-9bbf-6f8c71890b95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
