<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>6d2fcf2b-bc23-487f-9065-d57b54ac6c2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f9e82c31-aebc-47e4-af88-00f7a2a64fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>second-nav-url--KCXN5qu</value>
      <webElementGuid>e49da0fa-9522-4f6f-a40d-daf7be86cc49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>全部课程</value>
      <webElementGuid>64b4c03c-c941-4c80-bf07-9bf4ca80a10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;second-nav-wrap--3qtATEH&quot;]/div[@class=&quot;second-nav-content--2kkWcGI&quot;]/div[@class=&quot;second-nav-right--Zo54qF1&quot;]/span[@class=&quot;second-nav-url--KCXN5qu&quot;]</value>
      <webElementGuid>ea471216-aad4-4f18-a354-f0bca4b02a64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/span[2]</value>
      <webElementGuid>cd47e682-f592-41d3-8fa0-503e7fff664a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='首页'])[1]/following::span[1]</value>
      <webElementGuid>5a5a7388-a0de-4ca0-b740-916da0677f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='有效期：至2026-12-31'])[1]/following::span[2]</value>
      <webElementGuid>3aa63dce-a5dd-4478-a55b-8955c9bc9695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='今日任务'])[1]/preceding::span[1]</value>
      <webElementGuid>2b355afc-d5f2-499a-9064-fae79ddcf7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='全部任务'])[1]/preceding::span[1]</value>
      <webElementGuid>ac6da75f-c299-4eb5-bdc1-c8dc35ac9b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='全部课程']/parent::*</value>
      <webElementGuid>b4323c3b-0434-41ed-a30d-486098159a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>66ae339f-6f6a-43a9-819c-77485de2fa76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '全部课程' or . = '全部课程')]</value>
      <webElementGuid>d4276ac1-253a-48a7-b8ef-320c238bf2a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
