<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-clickliveclassname</name>
   <tag></tag>
   <elementGuidId>da6b5964-0f5e-4a59-805e-a841ed2363c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jp-content-wrap']/div/div/ul/li/ul/li/ul/div[2]/div[2]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span[title=&quot;勿动-【wrj自动化专用】巧记四六级核心词！&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;勿动-【wrj自动化专用】巧记四六级核心词！&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ce8a951e-b424-4d82-9291-478ab71983ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>勿动-【wrj自动化专用】巧记四六级核心词！</value>
      <webElementGuid>253f73df-7216-45da-85d4-70fcd282bf57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>勿动-【wrj自动化专用】巧记四六级核心词！</value>
      <webElementGuid>888bae91-87d2-408c-9272-cac2a6cc8e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jp-content-wrap&quot;)/div[@class=&quot;content-item jp-menu-wrap&quot;]/div[@class=&quot;list-container jp-list-container&quot;]/ul[@class=&quot;chapter&quot;]/li[@class=&quot;jp-filter&quot;]/ul[@class=&quot;bd jp-bd&quot;]/li[@class=&quot;sub-hd-wrap jp-node-wrap jp-filter&quot;]/ul[@class=&quot;sub-bd jp-sub-bd&quot;]/div[@class=&quot;class-item jp-class-item jp-filter&quot;]/div[@class=&quot;title&quot;]/div[@class=&quot;title__inner&quot;]/span[1]</value>
      <webElementGuid>3639b6e5-f24d-4972-bf69-db30a711eb2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jp-content-wrap']/div/div/ul/li/ul/li/ul/div[2]/div[2]/div/span</value>
      <webElementGuid>3df9bdba-1980-48c3-929b-2cc8222b08c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='毛中特选择题'])[1]/following::span[2]</value>
      <webElementGuid>e1bd6b00-8993-43e1-acb5-7ac2ff70f0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='更新中，课时：10'])[1]/following::span[3]</value>
      <webElementGuid>a3158a30-4706-434d-911f-a35508a67a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='上次学习'])[1]/preceding::span[1]</value>
      <webElementGuid>35f16086-f8ea-4b43-b91b-09139aaeeb3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='勿动-【wrj自动化专用】巧记四六级核心词！']/parent::*</value>
      <webElementGuid>03773cf8-5db2-414d-9180-60da82e5b5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/span</value>
      <webElementGuid>1a599dc7-ecd1-4b21-95a6-1f972bc5baed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = '勿动-【wrj自动化专用】巧记四六级核心词！' and (text() = '勿动-【wrj自动化专用】巧记四六级核心词！' or . = '勿动-【wrj自动化专用】巧记四六级核心词！')]</value>
      <webElementGuid>a69bf9fd-70ee-4363-8639-fcb2b5b6b806</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
