<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__dx-player-play-btn</name>
   <tag></tag>
   <elementGuidId>0ff0d4bb-a4f2-4950-8294-b4c3a6bb2383</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jp-player-wrap']/dx-player/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dx-player-play-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>52205f2e-801a-43fb-909c-20eaf2e2dd09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-player-play-btn</value>
      <webElementGuid>194f31d5-b6f4-4f96-8778-874fbb7a478e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jp-player-wrap&quot;)/dx-player[1]/div[@class=&quot;dx-player&quot;]/div[@class=&quot;dx-player-play-btn&quot;]</value>
      <webElementGuid>56ddf4dc-a729-40fa-93ba-40594ff276d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jp-player-wrap']/dx-player/div/div[3]</value>
      <webElementGuid>39c015b4-d13d-49f7-91f6-c90f1e2f74ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dx-player/div/div[3]</value>
      <webElementGuid>e8923672-56bb-49c4-9dc9-c710131c64f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
