<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1.2X-notok</name>
   <tag></tag>
   <elementGuidId>b1833a16-5957-4e43-bcad-4293e5bb9037</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>···</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d14ba9c2-ea33-4f86-97a4-ca3af58a708c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-select-dropdown-option-item-content</value>
      <webElementGuid>09d2fd08-a5bd-4d4b-9531-660e5a0e6d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1.2</value>
      <webElementGuid>e5fe267b-3fb2-45cf-b02a-1bd7f7e29c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>1.2X</value>
      <webElementGuid>582a0ac8-0e09-412e-bb96-9c8d0d781f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1.2X</value>
      <webElementGuid>cfad3ca2-366a-46db-8dc1-76838e666035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EDDCBDCBF14839000000953674&quot;)/div[5]/div[@class=&quot;dx-select-dropdown&quot;]/div[@class=&quot;dx-select-dropdown-option-item&quot;]/div[@class=&quot;dx-select-dropdown-option-item-content&quot;]</value>
      <webElementGuid>64f10b2c-b151-4aa1-8b29-19985abdffd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@value='1.2']</value>
      <webElementGuid>2cbcaebe-b5c2-400d-8e44-69cf895d5e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EDDCBDCBF14839000000953674']/div[5]/div/div[4]/div</value>
      <webElementGuid>22e40d1c-df0c-4b3a-88e8-f0bfdce946d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='取消'])[1]/following::div[12]</value>
      <webElementGuid>c4d3b8c3-6e2b-4966-a728-01a47bcd7d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='确认'])[1]/following::div[12]</value>
      <webElementGuid>9b1b6f3a-aad7-42b2-b502-0325f779e9ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='超清'])[1]/preceding::div[5]</value>
      <webElementGuid>93545590-105d-4ed8-8098-e2d2813a476f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='高清'])[1]/preceding::div[7]</value>
      <webElementGuid>8df9c9d9-1066-4068-a90e-9b09b85a1a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1.2X']/parent::*</value>
      <webElementGuid>251adec2-ea23-4497-9a08-c30989c91bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div</value>
      <webElementGuid>3c5cbee6-96bc-488b-8cba-f511e934e26c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = '1.2X' and (text() = '1.2X' or . = '1.2X')]</value>
      <webElementGuid>206bdd88-16af-4272-81df-b82ab6b02889</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
