<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__dx-player-controller-progress</name>
   <tag></tag>
   <elementGuidId>ac83a97f-47b3-4d97-a1e7-99999716e10a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jp-player-wrap']/dx-player/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dx-player-controller-progress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fdbbd1a2-3b41-42db-8765-40d6f57f97a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-player-controller-progress</value>
      <webElementGuid>27cfc161-8670-4133-b313-ae34f0802b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jp-player-wrap&quot;)/dx-player[1]/div[@class=&quot;dx-player&quot;]/div[@class=&quot;dx-player-controller&quot;]/div[@class=&quot;dx-player-controller-progress&quot;]</value>
      <webElementGuid>89adeef9-b9eb-4ca1-87df-c1829fc370a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jp-player-wrap']/dx-player/div/div[2]/div</value>
      <webElementGuid>4f775734-626f-41a8-8683-9776e88dde49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='流畅'])[3]/following::div[30]</value>
      <webElementGuid>eb014e06-4bea-410c-92b7-6c5146820c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='标清'])[3]/following::div[32]</value>
      <webElementGuid>b7843161-61ba-4940-a1d4-a28e0adecd3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/preceding::div[13]</value>
      <webElementGuid>55ddbe96-c98a-40ed-b041-f63e64f881ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='超清'])[4]/preceding::div[16]</value>
      <webElementGuid>2ff42d1d-37f1-479c-88eb-c2de743cf485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dx-player/div/div[2]/div</value>
      <webElementGuid>d0cfda97-1aae-4589-9a01-a14239274e11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
