<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dx-speed-notok</name>
   <tag></tag>
   <elementGuidId>c62a8bf4-4e08-4033-94ca-ffe90d982944</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//dx-popover[@value='1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>dx-popover[value=&quot;1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>dx-popover</value>
      <webElementGuid>a9a81609-df77-4e0c-865d-4628772d5c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ssrtag</name>
      <type>Main</type>
      <value>EDDCBDCBF14839000000953674</value>
      <webElementGuid>1dc7e8af-01f0-486e-affc-72b0282777d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9028e3bd-aa49-4ee1-a478-ba59a7369402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2.0X1.8X1.5X1.2X1.0X0.8X</value>
      <webElementGuid>0bb6ac9a-8aea-4ce0-adee-818c102075d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jp-player-wrap&quot;)/dx-player[1]/div[@class=&quot;dx-player&quot;]/div[@class=&quot;dx-player-controller&quot;]/div[@class=&quot;dx-player-controller-bottom&quot;]/div[@class=&quot;dx-player-controller-bottom-right&quot;]/div[@class=&quot;dx-player-controller-bottom-right-speed&quot;]/dx-popover[1]</value>
      <webElementGuid>64af8767-d855-4178-8e5c-a8318c1411f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//dx-popover[@value='1']</value>
      <webElementGuid>faee33c3-bae2-447b-9da1-2ee623efe47a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jp-player-wrap']/dx-player/div/div[2]/div[2]/div[2]/div[3]/dx-popover</value>
      <webElementGuid>ffe4b5f7-8a97-4ca8-b75d-abf0a2da6931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='知识点'])[1]/following::dx-popover[1]</value>
      <webElementGuid>72195aaf-9440-46e9-b5db-6cc76e8962ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='流畅'])[4]/following::dx-popover[1]</value>
      <webElementGuid>00a868f1-ba4f-48d1-a3ae-b552e368247a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='测试题纲测试题纲测试题纲测试题纲测试题纲测试题纲测试题纲测试题纲测试题纲测试题纲测试题纲测'])[1]/preceding::dx-popover[1]</value>
      <webElementGuid>1e8696c8-b5ad-4e2d-b0e4-35cd7578a46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='词汇测u25-5'])[1]/preceding::dx-popover[1]</value>
      <webElementGuid>307aaa82-a1d2-4b3f-9cc5-bb72b4b148bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/dx-popover</value>
      <webElementGuid>2d02ef3c-5923-4985-9058-579d36001a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//dx-popover[(text() = '2.0X1.8X1.5X1.2X1.0X0.8X' or . = '2.0X1.8X1.5X1.2X1.0X0.8X')]</value>
      <webElementGuid>8f65e281-8872-4f08-a8c2-d519ff18fdaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
