<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video</name>
   <tag></tag>
   <elementGuidId>05ed2de3-1153-4c84-8be5-ecdf8569aade</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='EDDCBDCBF14839000000953674']/video</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>video</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>ab08b430-c0f6-4ab6-8edf-8c69e565286c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preload</name>
      <type>Main</type>
      <value>preload</value>
      <webElementGuid>62ac5db9-f46a-44b8-88a4-bf8849973bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>controls</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>845a452e-d20d-4901-98a3-bfdcc2b06be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>blob:https://study.koolearn.com/44e17f3e-3b4c-4021-b16e-050350093d11</value>
      <webElementGuid>53d3888f-a42c-41f4-812e-afbc546f9f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EDDCBDCBF14839000000953674&quot;)/video[1]</value>
      <webElementGuid>be1a71d7-94c0-4f8f-8d1f-8643f4e04e9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EDDCBDCBF14839000000953674']/video</value>
      <webElementGuid>ed6e8113-edfd-4674-976f-e65e1516a240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>bd941c1e-3346-4d49-b662-5d4dcb79d4b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@src = 'blob:https://study.koolearn.com/44e17f3e-3b4c-4021-b16e-050350093d11']</value>
      <webElementGuid>32879817-2c53-4ddf-8937-79a293d32131</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
