<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_speed</name>
   <tag></tag>
   <elementGuidId>1a4463f9-3c19-4145-83c3-f709fd47353d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xdf-player_component_E3C78F28-D302-4B97-8E97-917DE5833871']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.current-speed-selector</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;倍速&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9af15e3a-c22b-413d-8b97-071b87b8d03b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>current-speed-selector</value>
      <webElementGuid>194523e8-5dbe-41d7-bf92-adfcd9efd260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>key</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c8c4d2ad-7c34-45f6-829c-4ad0b86f79b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>dba6a1f0-52b9-4267-80cf-22b9f49d1a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>倍速</value>
      <webElementGuid>b7487af2-b63e-4e7a-954a-f9d98907ecc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xdf-player_component_E3C78F28-D302-4B97-8E97-917DE5833871&quot;)/div[@class=&quot;current-speed-selector&quot;]</value>
      <webElementGuid>cf96da69-6c7e-44bc-8877-b448760d0b29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xdf-player_component_E3C78F28-D302-4B97-8E97-917DE5833871']/div</value>
      <webElementGuid>afa3dd20-3a18-455b-9b0b-88411bca8221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/following::div[3]</value>
      <webElementGuid>d368860f-cc80-4fe5-88b2-1abc4263aea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='正常'])[1]/preceding::div[2]</value>
      <webElementGuid>c690a619-b924-4867-ac0f-2fa088aedb3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='确认'])[1]/preceding::div[14]</value>
      <webElementGuid>9d7be96f-4a9c-4cc0-b716-e9061b9f6609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='倍速']/parent::*</value>
      <webElementGuid>d0e4091c-6f03-46d8-8f74-e8acedb884c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>1b0d35bb-0390-4d98-a2b4-353edd303260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '倍速' or . = '倍速')]</value>
      <webElementGuid>8b088e55-01fb-4257-941d-1cda01828abb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
