<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1.25X</name>
   <tag></tag>
   <elementGuidId>2679e6ab-a594-424b-8fe4-c264f2fe1c94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xdf-player_component_E3C78F28-D302-4B97-8E97-917DE5833871']/ul/li[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.speed-selector-list > li:nth-of-type(3) > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;1.25X&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>73312eeb-a2a3-4b6c-9f19-db3eb7cb6df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1.25X</value>
      <webElementGuid>6ae5180b-4bf8-4344-b0bd-0da961b45914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xdf-player_component_E3C78F28-D302-4B97-8E97-917DE5833871&quot;)/ul[@class=&quot;speed-selector-list&quot;]/li[3]/span[1]</value>
      <webElementGuid>68d0c0fb-69ed-4582-aba3-119df57f6be3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xdf-player_component_E3C78F28-D302-4B97-8E97-917DE5833871']/ul/li[3]/span</value>
      <webElementGuid>c1667385-b6b6-4a06-8fff-ecf219f402ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='正常'])[1]/following::span[1]</value>
      <webElementGuid>1953caa4-3de7-4ee9-9c4b-ef6fe751a83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='倍速'])[1]/following::span[3]</value>
      <webElementGuid>39aaa344-f4b2-45f8-9fde-f6e616ef37da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='确认'])[1]/preceding::span[3]</value>
      <webElementGuid>5b629a3f-93bb-43e5-9081-5217f195dc27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='取消'])[2]/preceding::span[3]</value>
      <webElementGuid>0f1df6a1-885a-4a8b-999c-8ba1fc59fea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1.25X']/parent::*</value>
      <webElementGuid>4be8a3d6-9332-4b56-889a-30cefe3f9f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/ul/li[3]/span</value>
      <webElementGuid>9dc98a02-d595-4c50-bad8-b98ca1d55e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1.25X' or . = '1.25X')]</value>
      <webElementGuid>c9c4b2ce-c465-414a-af2d-183f5554384c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
