<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video</name>
   <tag></tag>
   <elementGuidId>7edebc1c-0f78-419b-81ec-818d19112cdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='EDDCBDCBF12785']/video</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>video</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>f43dfed6-677b-41cc-a818-9edd9271e8e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preload</name>
      <type>Main</type>
      <value>preload</value>
      <webElementGuid>7e6964b8-b1d8-41e8-9d47-14b143f4db02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>controls</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>46085612-289f-4534-bf85-e0d9f551a909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>blob:https://study.koolearn.com/99aea5a4-e5ca-4af6-b524-f50eac1fdc1d</value>
      <webElementGuid>d7d5c797-523f-47d2-ae95-0c7b685a3935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EDDCBDCBF12785&quot;)/video[1]</value>
      <webElementGuid>f997cd1a-64ae-4bde-889d-b12d90f22ff2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EDDCBDCBF12785']/video</value>
      <webElementGuid>93bf12c8-91c9-4acd-b4c6-47fc022cda37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>291cfb43-84f5-4679-85a2-f72e9bc76ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@src = 'blob:https://study.koolearn.com/99aea5a4-e5ca-4af6-b524-f50eac1fdc1d']</value>
      <webElementGuid>e2138a71-2209-431d-bc9b-1957cfa97226</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
